[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jax_expand"
version = "0.0.1"
description = "Expanding weight matrices in Jax"
authors = [{name="Daniel CH Tan", email="dtch1997@users.noreply.github.com"}]
license = "MIT"
readme = "README.md"